// T-39 — the seven honest display rules, shared chrome (ported from
// web/forkmap/app.js LANDING_RULES + ruleList). The ids honest-rule-1…7 must
// survive in the rendered DOM 1:1 (id-coverage is parity-asserted).

export const LANDING_RULES = [
  "Epochs are exact-copy-only within a stream: the matrix cells and dots are the whole story; equal surfaces never span two forks in the current data.",
  "The item model is kind:name with module paths where the corpus walks pub mod chains (root re-exports stay flat — struct:Window); fn digests are parameter-type level (a parameter rename never re-signs); doc comments count toward a type's digest, so a doc-only change reads as a re-signature.",
  "Methods and associated items of public types are measured since T-26 (2026-09-07), and each entry carries its effective cfg gates as provenance; derives, trait-interface items, external-crate members and cfg evaluation are outside the measured item model — where a view would need them it says “outside the measured item model” and never infers compatibility.",
  "An unmeasured row renders “not measured” — never as an absence or a non-change.",
  "“Compile-verified” badges appear only where the studies compiled real artifacts, and every badge links its evidence (docs 07 / 12).",
  "Yanked and prerelease rows are shown and flagged; a prerelease is never presented as a stable choice (the default is the latest stable).",
  "Every claim traces to the dataset — this page is generated by cargo gocar export-fork-map and computes all counts from the loaded bundle.",
];

export function RuleList({ full }: { full?: boolean }) {
  const short = [
    "no cross-fork “same generation” badges, ever — the cells and dots are the whole story; cross-fork Changes deltas are snapshot-surface differences, never changelogs, with rule rows informational only.",
    "items are kind:name with module paths where the corpus walks pub mod chains (root re-exports stay flat); fn digests are parameter-type; doc comments count toward a type's digest, so a doc-only edit re-signs.",
    "methods and associated items of public types are measured (T-26); derives, trait-interface items, external-crate members and cfg evaluation are not — never inferred.",
    "null ≠ unchanged: unmeasured rows render “not measured”.",
    "“compiles” badges only where the studies compiled real artifacts, each linked to its evidence.",
    "yanked + prerelease rows are flagged; a prerelease is never a default choice.",
    "every claim traces to the dataset; nothing here is hand-edited.",
  ];
  return (
    <ol className="rules">
      {LANDING_RULES.map((text, i) => (
        <li key={i} id={`honest-rule-${i + 1}`}>
          <strong>{full ? `Rule ${i + 1}.` : `Rule ${i + 1} —`}</strong> {full ? text : short[i]}
        </li>
      ))}
    </ol>
  );
}
